export const NEW_PRODUCT_LIST = "NEW_PRODUCT_LIST";
export const IPHONE_LIST = "IPHONE_LIST";
export const IPAD_LIST = "IPAD_LIST";
export const SAVE_IMAGES = "SAVE_IMAGES";

export const GET_PRODUCT_CART = "GET_PRODUCT_CART";
export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const REMOVE_PRODUCT_CART = "REMOVE_PRODUCT_CART";
export const REMOVE_CART = "REMOVE_CART";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGIN_LOGOUT";
export const UPDATE_USER = "UPDATE_USER";

export const REVIEW_LIST = "REVIEW_LIST";
