export const NEW_PRODUCT_LIST = "NEW_PRODUCT_LIST";
export const IPHONE_LIST = "IPHONE_LIST";
export const IPAD_LIST = "IPAD_LIST";
export const SAVE_IMAGES = "SAVE_IMAGES";

export const GET_PRODUCT_CART = "GET_PRODUCT_CART";
export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const REMOVE_PRODUCT_CART = "REMOVE_PRODUCT_CART";
export const REMOVE_CART = "REMOVE_CART";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
